language: node_js
node_js:
  - node
before_script:
  - npm install -g grunt
notifications:
  email:
    on_success: change
    on_failure: always
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
